let suggestions = [
	'Youtube',
	'Desarrollador Web',
	'Diseñador Web',
	'Formularios con HTML y CSS',
	'Crear un canal en Youtube',
	'Dinero en la programación',
	'Programación en Python',
	'Desarrollo Frontend',
	'Desarrollo Backend',
	'Rest api con Nodejs',
	'Como crear un blog con Django',
	'Como crear un sitio web responsive',
	'Como consumir una api con React',
	'Aprender React desde cero',
	'Aprender Css desde cero',
	'Aprender Html desde cero',
	'Como convertirse en programador rapidamente',
	'Aprender python desde cero',
];
